title: Standard-Seite

# options
options:
  changeSlug: true
  changeStatus: true
  changeTemplate:
    - default
    - defaultsubs
    - defaultsubsfranch
    - franchisee
  changeTitle: true
  create: true
  delete: true
  duplicate: true
  move: true
  preview: true
  sort: true
  update: true

# fields
tabs:
  content:
    label:
      en: Content
      de: Inhalt
    icon: layers
    columns:
      colA: 
        width: 1/1
        sections:
          scA:
            type: fields
            fields:
              contents:
                label:
                  en: Content
                  de: Inhalt
                type: blocks
                fieldsets:
                  - grid

  #SEO
  seo: seo/page